# Generated by Django 5.0.4 on 2024-04-26 09:52

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

import json
from thai.models import Province, District, SubDistrict


def load_file(apps, schema_editor):
    with open("thai/seed/loc_provinces.json", encoding="utf8") as f:
        loc_provinces = json.load(f)
    for data in loc_provinces:
        data["pk"] = data.pop("id")
        data.pop("created_at")
        data.pop("updated_at")
        data.pop("geography_id")
        Province.objects.get_or_create(pk=data["pk"], defaults=data)

    with open("thai/seed/loc_districts.json", encoding="utf8") as f:
        loc_districts = json.load(f)
    for data in loc_districts:
        data["pk"] = data.pop("id")
        data.pop("created_at")
        data.pop("updated_at")
        data["province"] = Province.objects.get(pk=data.pop("province_id"))
        District.objects.get_or_create(pk=data["pk"], defaults=data)

    with open("thai/seed/loc_sub_districts.json", encoding="utf8") as f:
        loc_sub_districts = json.load(f)
    for data in loc_sub_districts:
        data["pk"] = data.pop("id")
        data.pop("created_at")
        data.pop("updated_at")
        data["district"] = District.objects.get(pk=data.pop("district_id"))
        SubDistrict.objects.get_or_create(pk=data["pk"], defaults=data)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100)),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="thai.province"
                    ),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SubDistrict",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100)),
                ("zipcode", models.CharField(max_length=10)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="thai.district"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-District",
                "verbose_name_plural": "Sub-Districts",
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(load_file, None),
    ]
